# baseurl: https://leandroc.github.io
baseurl: /

timezone:	America/Sao_Paulo

highlighter: rouge

sass:
  style: compressed
  sass_dir: _sass

excerpt_separator: <!-- more -->
permalink: /blog/:year/:month/:title.html

paginate: 5
paginate_path: "/blog/page-:num/"

# pagination:
#   enabled: true
#   sort_reverse: true
#   per_page: 5
#   collection: 'posts'
#   permalink: '/blog/page-:num/'

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-paginate
